
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AdminSidebar': typeof import("../../veloris-dashboard/components/AdminSidebar.vue")['default']
    'AdminTopbar': typeof import("../../veloris-dashboard/components/AdminTopbar.vue")['default']
    'CalendlyEmbed': typeof import("../../veloris-dashboard/components/CalendlyEmbed.vue")['default']
    'Chatroom': typeof import("../../veloris-dashboard/components/Chatroom.vue")['default']
    'GravLoader': typeof import("../../veloris-dashboard/components/GravLoader.vue")['default']
    'NavDesktopNav': typeof import("../../veloris-dashboard/components/Nav/DesktopNav.vue")['default']
    'NavMobileNav': typeof import("../../veloris-dashboard/components/Nav/MobileNav.vue")['default']
    'Nav': typeof import("../../veloris-dashboard/components/Nav/Nav.vue")['default']
    'NotificationDropdown': typeof import("../../veloris-dashboard/components/NotificationDropdown.vue")['default']
    'Orders': typeof import("../../veloris-dashboard/components/Orders/orders.vue")['default']
    'AddItemDiscardModal': typeof import("../../veloris-dashboard/components/add-item/discard-modal.vue")['default']
    'AddItemImageInputs': typeof import("../../veloris-dashboard/components/add-item/image-inputs.vue")['default']
    'AddItemForm': typeof import("../../veloris-dashboard/components/add-item/item-form.vue")['default']
    'AddItemTags': typeof import("../../veloris-dashboard/components/add-item/tags.vue")['default']
    'AddItemVariations': typeof import("../../veloris-dashboard/components/add-item/variations.vue")['default']
    'AdminDialogs': typeof import("../../veloris-dashboard/components/admin-dialogs.vue")['default']
    'AnalyticsActiveUsersLast30Minutes': typeof import("../../veloris-dashboard/components/analytics/ActiveUsersLast30Minutes.vue")['default']
    'AnalyticsAverageSessionDuration': typeof import("../../veloris-dashboard/components/analytics/AverageSessionDuration.vue")['default']
    'AnalyticsBounceRateByDate': typeof import("../../veloris-dashboard/components/analytics/BounceRateByDate.vue")['default']
    'AnalyticsTotalUsers': typeof import("../../veloris-dashboard/components/analytics/TotalUsers.vue")['default']
    'AnalyticsUsersByChannel': typeof import("../../veloris-dashboard/components/analytics/UsersByChannel.vue")['default']
    'AnalyticsUsersByDate': typeof import("../../veloris-dashboard/components/analytics/UsersByDate.vue")['default']
    'AnalyticsUsersByDeviceChart': typeof import("../../veloris-dashboard/components/analytics/UsersByDeviceChart.vue")['default']
    'AnalyticsViewsByPage': typeof import("../../veloris-dashboard/components/analytics/ViewsByPage.vue")['default']
    'AnalyticsSectionTwo': typeof import("../../veloris-dashboard/components/analytics/section-two.vue")['default']
    'AnalyticsTopSection': typeof import("../../veloris-dashboard/components/analytics/top-section.vue")['default']
    'BlogsEditorPage': typeof import("../../veloris-dashboard/components/blogs/EditorPage.vue")['default']
    'DashboardMessages': typeof import("../../veloris-dashboard/components/dashboard/Messages.vue")['default']
    'DashboardHeader': typeof import("../../veloris-dashboard/components/dashboard/dashboard-header.vue")['default']
    'DashboardFooter': typeof import("../../veloris-dashboard/components/dashboard/footer.vue")['default']
    'DashboardLoader': typeof import("../../veloris-dashboard/components/dashboard/loader.vue")['default']
    'DashboardModals': typeof import("../../veloris-dashboard/components/dashboard/modals.vue")['default']
    'DashboardWelcome': typeof import("../../veloris-dashboard/components/dashboard/welcome.vue")['default']
    'StoreProductCard': typeof import("../../veloris-dashboard/components/store/product-card.vue")['default']
    'VelorisHello': typeof import("../../veloris-dashboard/components/veloris-hello.vue")['default']
    'Acc': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/acc.vue")['default']
    'Aft': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/aft.vue")['default']
    'Alert': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/alert.vue")['default']
    'Anchor': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/anchor.vue")['default']
    'Bigrid': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/bigrid.vue")['default']
    'Binav': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/binav.vue")['default']
    'Blognav': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/blognav.vue")['default']
    'Breadcrumbs': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/breadcrumbs.vue")['default']
    'Btn': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/btn.vue")['default']
    'Burger': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/burger.vue")['default']
    'ButtonGroup': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/button-group.vue")['default']
    'Cardgrid': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cardgrid.vue")['default']
    'Carousel': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/carousel.vue")['default']
    'Cflex': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cflex.vue")['default']
    'Checkbox': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/checkbox.vue")['default']
    'Chip': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/chip.vue")['default']
    'Chips': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/chips.vue")['default']
    'Column': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/column.vue")['default']
    'ConfirmPassword': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/confirm-password.vue")['default']
    'Content': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/content.vue")['default']
    'CounterInput': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/counter-input.vue")['default']
    'CursorTooltip': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cursor-tooltip.vue")['default']
    'Cursor': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cursor.vue")['default']
    'CustomCss': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/custom-css")['default']
    'Discord': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/discord.vue")['default']
    'DragDiv': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/drag-div.vue")['default']
    'Drop': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/drop.vue")['default']
    'EmailOld': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/email.old.vue")['default']
    'Email': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/email.vue")['default']
    'Error': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/error.vue")['default']
    'Facebook': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/facebook.vue")['default']
    'Field': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/field.vue")['default']
    'Fillout': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/fillout.vue")['default']
    'Flareframe': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/flareframe.vue")['default']
    'Fore': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/fore.vue")['default']
    'Github': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/github.vue")['default']
    'GoogleMap': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/google-map.vue")['default']
    'Grid': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/grid.vue")['default']
    'InfiniteColumn': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/infinite-column.vue")['default']
    'InfiniteRow': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/infinite-row.vue")['default']
    'Instagram': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/instagram.vue")['default']
    'Lchips': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lchips.vue")['default']
    'LeftButton': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/left-button.vue")['default']
    'Lheader': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lheader.vue")['default']
    'LighthouseCircle': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lighthouse-circle.vue")['default']
    'Linkedin': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/linkedin.vue")['default']
    'Loader': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/loader.vue")['default']
    'LogoRolls': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/logo-rolls.vue")['default']
    'Message': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/message.vue")['default']
    'Mflex': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mflex.vue")['default']
    'Mheader': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mheader.vue")['default']
    'Mnav': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mnav.vue")['default']
    'Modal': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/modal.vue")['default']
    'Mpage': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mpage.vue")['default']
    'Name': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/name.vue")['default']
    'NovaInput': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/nova-input.vue")['default']
    'Pages': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/pages.vue")['default']
    'Password': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/password.vue")['default']
    'Rchips': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rchips.vue")['default']
    'Rflex': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rflex.vue")['default']
    'Rheader': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rheader.vue")['default']
    'RightButton': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/right-button.vue")['default']
    'Row': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/row.vue")['default']
    'Search': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/search.vue")['default']
    'Splitrow': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/splitrow.vue")['default']
    'StickyBox': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/sticky-box.vue")['default']
    'StickyContent': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/sticky-content.vue")['default']
    'Submit': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/submit.vue")['default']
    'Success': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/success.vue")['default']
    'Tab': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tab.vue")['default']
    'Tabs': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tabs.vue")['default']
    'Tag': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tag.vue")['default']
    'Toggle': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/toggle.vue")['default']
    'Tooltip': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tooltip.vue")['default']
    'Trigrid': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/trigrid.vue")['default']
    'Trinav': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/trinav.vue")['default']
    'Twitter': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/twitter.vue")['default']
    'TypewriterReplace': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/typewriter-replace.vue")['default']
    'Typewriter': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/typewriter.vue")['default']
    'Whatsapp': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/whatsapp.vue")['default']
    'YoutubeVideo': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/youtube-video.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAdminSidebar': typeof import("../../veloris-dashboard/components/AdminSidebar.vue")['default']
    'LazyAdminTopbar': typeof import("../../veloris-dashboard/components/AdminTopbar.vue")['default']
    'LazyCalendlyEmbed': typeof import("../../veloris-dashboard/components/CalendlyEmbed.vue")['default']
    'LazyChatroom': typeof import("../../veloris-dashboard/components/Chatroom.vue")['default']
    'LazyGravLoader': typeof import("../../veloris-dashboard/components/GravLoader.vue")['default']
    'LazyNavDesktopNav': typeof import("../../veloris-dashboard/components/Nav/DesktopNav.vue")['default']
    'LazyNavMobileNav': typeof import("../../veloris-dashboard/components/Nav/MobileNav.vue")['default']
    'LazyNav': typeof import("../../veloris-dashboard/components/Nav/Nav.vue")['default']
    'LazyNotificationDropdown': typeof import("../../veloris-dashboard/components/NotificationDropdown.vue")['default']
    'LazyOrders': typeof import("../../veloris-dashboard/components/Orders/orders.vue")['default']
    'LazyAddItemDiscardModal': typeof import("../../veloris-dashboard/components/add-item/discard-modal.vue")['default']
    'LazyAddItemImageInputs': typeof import("../../veloris-dashboard/components/add-item/image-inputs.vue")['default']
    'LazyAddItemForm': typeof import("../../veloris-dashboard/components/add-item/item-form.vue")['default']
    'LazyAddItemTags': typeof import("../../veloris-dashboard/components/add-item/tags.vue")['default']
    'LazyAddItemVariations': typeof import("../../veloris-dashboard/components/add-item/variations.vue")['default']
    'LazyAdminDialogs': typeof import("../../veloris-dashboard/components/admin-dialogs.vue")['default']
    'LazyAnalyticsActiveUsersLast30Minutes': typeof import("../../veloris-dashboard/components/analytics/ActiveUsersLast30Minutes.vue")['default']
    'LazyAnalyticsAverageSessionDuration': typeof import("../../veloris-dashboard/components/analytics/AverageSessionDuration.vue")['default']
    'LazyAnalyticsBounceRateByDate': typeof import("../../veloris-dashboard/components/analytics/BounceRateByDate.vue")['default']
    'LazyAnalyticsTotalUsers': typeof import("../../veloris-dashboard/components/analytics/TotalUsers.vue")['default']
    'LazyAnalyticsUsersByChannel': typeof import("../../veloris-dashboard/components/analytics/UsersByChannel.vue")['default']
    'LazyAnalyticsUsersByDate': typeof import("../../veloris-dashboard/components/analytics/UsersByDate.vue")['default']
    'LazyAnalyticsUsersByDeviceChart': typeof import("../../veloris-dashboard/components/analytics/UsersByDeviceChart.vue")['default']
    'LazyAnalyticsViewsByPage': typeof import("../../veloris-dashboard/components/analytics/ViewsByPage.vue")['default']
    'LazyAnalyticsSectionTwo': typeof import("../../veloris-dashboard/components/analytics/section-two.vue")['default']
    'LazyAnalyticsTopSection': typeof import("../../veloris-dashboard/components/analytics/top-section.vue")['default']
    'LazyBlogsEditorPage': typeof import("../../veloris-dashboard/components/blogs/EditorPage.vue")['default']
    'LazyDashboardMessages': typeof import("../../veloris-dashboard/components/dashboard/Messages.vue")['default']
    'LazyDashboardHeader': typeof import("../../veloris-dashboard/components/dashboard/dashboard-header.vue")['default']
    'LazyDashboardFooter': typeof import("../../veloris-dashboard/components/dashboard/footer.vue")['default']
    'LazyDashboardLoader': typeof import("../../veloris-dashboard/components/dashboard/loader.vue")['default']
    'LazyDashboardModals': typeof import("../../veloris-dashboard/components/dashboard/modals.vue")['default']
    'LazyDashboardWelcome': typeof import("../../veloris-dashboard/components/dashboard/welcome.vue")['default']
    'LazyStoreProductCard': typeof import("../../veloris-dashboard/components/store/product-card.vue")['default']
    'LazyVelorisHello': typeof import("../../veloris-dashboard/components/veloris-hello.vue")['default']
    'LazyAcc': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/acc.vue")['default']
    'LazyAft': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/aft.vue")['default']
    'LazyAlert': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/alert.vue")['default']
    'LazyAnchor': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/anchor.vue")['default']
    'LazyBigrid': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/bigrid.vue")['default']
    'LazyBinav': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/binav.vue")['default']
    'LazyBlognav': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/blognav.vue")['default']
    'LazyBreadcrumbs': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/breadcrumbs.vue")['default']
    'LazyBtn': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/btn.vue")['default']
    'LazyBurger': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/burger.vue")['default']
    'LazyButtonGroup': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/button-group.vue")['default']
    'LazyCardgrid': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cardgrid.vue")['default']
    'LazyCarousel': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/carousel.vue")['default']
    'LazyCflex': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cflex.vue")['default']
    'LazyCheckbox': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/checkbox.vue")['default']
    'LazyChip': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/chip.vue")['default']
    'LazyChips': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/chips.vue")['default']
    'LazyColumn': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/column.vue")['default']
    'LazyConfirmPassword': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/confirm-password.vue")['default']
    'LazyContent': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/content.vue")['default']
    'LazyCounterInput': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/counter-input.vue")['default']
    'LazyCursorTooltip': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cursor-tooltip.vue")['default']
    'LazyCursor': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cursor.vue")['default']
    'LazyCustomCss': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/custom-css")['default']
    'LazyDiscord': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/discord.vue")['default']
    'LazyDragDiv': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/drag-div.vue")['default']
    'LazyDrop': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/drop.vue")['default']
    'LazyEmailOld': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/email.old.vue")['default']
    'LazyEmail': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/email.vue")['default']
    'LazyError': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/error.vue")['default']
    'LazyFacebook': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/facebook.vue")['default']
    'LazyField': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/field.vue")['default']
    'LazyFillout': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/fillout.vue")['default']
    'LazyFlareframe': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/flareframe.vue")['default']
    'LazyFore': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/fore.vue")['default']
    'LazyGithub': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/github.vue")['default']
    'LazyGoogleMap': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/google-map.vue")['default']
    'LazyGrid': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/grid.vue")['default']
    'LazyInfiniteColumn': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/infinite-column.vue")['default']
    'LazyInfiniteRow': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/infinite-row.vue")['default']
    'LazyInstagram': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/instagram.vue")['default']
    'LazyLchips': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lchips.vue")['default']
    'LazyLeftButton': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/left-button.vue")['default']
    'LazyLheader': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lheader.vue")['default']
    'LazyLighthouseCircle': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lighthouse-circle.vue")['default']
    'LazyLinkedin': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/linkedin.vue")['default']
    'LazyLoader': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/loader.vue")['default']
    'LazyLogoRolls': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/logo-rolls.vue")['default']
    'LazyMessage': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/message.vue")['default']
    'LazyMflex': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mflex.vue")['default']
    'LazyMheader': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mheader.vue")['default']
    'LazyMnav': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mnav.vue")['default']
    'LazyModal': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/modal.vue")['default']
    'LazyMpage': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mpage.vue")['default']
    'LazyName': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/name.vue")['default']
    'LazyNovaInput': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/nova-input.vue")['default']
    'LazyPages': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/pages.vue")['default']
    'LazyPassword': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/password.vue")['default']
    'LazyRchips': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rchips.vue")['default']
    'LazyRflex': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rflex.vue")['default']
    'LazyRheader': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rheader.vue")['default']
    'LazyRightButton': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/right-button.vue")['default']
    'LazyRow': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/row.vue")['default']
    'LazySearch': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/search.vue")['default']
    'LazySplitrow': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/splitrow.vue")['default']
    'LazyStickyBox': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/sticky-box.vue")['default']
    'LazyStickyContent': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/sticky-content.vue")['default']
    'LazySubmit': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/submit.vue")['default']
    'LazySuccess': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/success.vue")['default']
    'LazyTab': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tab.vue")['default']
    'LazyTabs': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tabs.vue")['default']
    'LazyTag': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tag.vue")['default']
    'LazyToggle': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/toggle.vue")['default']
    'LazyTooltip': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tooltip.vue")['default']
    'LazyTrigrid': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/trigrid.vue")['default']
    'LazyTrinav': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/trinav.vue")['default']
    'LazyTwitter': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/twitter.vue")['default']
    'LazyTypewriterReplace': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/typewriter-replace.vue")['default']
    'LazyTypewriter': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/typewriter.vue")['default']
    'LazyWhatsapp': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/whatsapp.vue")['default']
    'LazyYoutubeVideo': typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/youtube-video.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AdminSidebar: typeof import("../../veloris-dashboard/components/AdminSidebar.vue")['default']
export const AdminTopbar: typeof import("../../veloris-dashboard/components/AdminTopbar.vue")['default']
export const CalendlyEmbed: typeof import("../../veloris-dashboard/components/CalendlyEmbed.vue")['default']
export const Chatroom: typeof import("../../veloris-dashboard/components/Chatroom.vue")['default']
export const GravLoader: typeof import("../../veloris-dashboard/components/GravLoader.vue")['default']
export const NavDesktopNav: typeof import("../../veloris-dashboard/components/Nav/DesktopNav.vue")['default']
export const NavMobileNav: typeof import("../../veloris-dashboard/components/Nav/MobileNav.vue")['default']
export const Nav: typeof import("../../veloris-dashboard/components/Nav/Nav.vue")['default']
export const NotificationDropdown: typeof import("../../veloris-dashboard/components/NotificationDropdown.vue")['default']
export const Orders: typeof import("../../veloris-dashboard/components/Orders/orders.vue")['default']
export const AddItemDiscardModal: typeof import("../../veloris-dashboard/components/add-item/discard-modal.vue")['default']
export const AddItemImageInputs: typeof import("../../veloris-dashboard/components/add-item/image-inputs.vue")['default']
export const AddItemForm: typeof import("../../veloris-dashboard/components/add-item/item-form.vue")['default']
export const AddItemTags: typeof import("../../veloris-dashboard/components/add-item/tags.vue")['default']
export const AddItemVariations: typeof import("../../veloris-dashboard/components/add-item/variations.vue")['default']
export const AdminDialogs: typeof import("../../veloris-dashboard/components/admin-dialogs.vue")['default']
export const AnalyticsActiveUsersLast30Minutes: typeof import("../../veloris-dashboard/components/analytics/ActiveUsersLast30Minutes.vue")['default']
export const AnalyticsAverageSessionDuration: typeof import("../../veloris-dashboard/components/analytics/AverageSessionDuration.vue")['default']
export const AnalyticsBounceRateByDate: typeof import("../../veloris-dashboard/components/analytics/BounceRateByDate.vue")['default']
export const AnalyticsTotalUsers: typeof import("../../veloris-dashboard/components/analytics/TotalUsers.vue")['default']
export const AnalyticsUsersByChannel: typeof import("../../veloris-dashboard/components/analytics/UsersByChannel.vue")['default']
export const AnalyticsUsersByDate: typeof import("../../veloris-dashboard/components/analytics/UsersByDate.vue")['default']
export const AnalyticsUsersByDeviceChart: typeof import("../../veloris-dashboard/components/analytics/UsersByDeviceChart.vue")['default']
export const AnalyticsViewsByPage: typeof import("../../veloris-dashboard/components/analytics/ViewsByPage.vue")['default']
export const AnalyticsSectionTwo: typeof import("../../veloris-dashboard/components/analytics/section-two.vue")['default']
export const AnalyticsTopSection: typeof import("../../veloris-dashboard/components/analytics/top-section.vue")['default']
export const BlogsEditorPage: typeof import("../../veloris-dashboard/components/blogs/EditorPage.vue")['default']
export const DashboardMessages: typeof import("../../veloris-dashboard/components/dashboard/Messages.vue")['default']
export const DashboardHeader: typeof import("../../veloris-dashboard/components/dashboard/dashboard-header.vue")['default']
export const DashboardFooter: typeof import("../../veloris-dashboard/components/dashboard/footer.vue")['default']
export const DashboardLoader: typeof import("../../veloris-dashboard/components/dashboard/loader.vue")['default']
export const DashboardModals: typeof import("../../veloris-dashboard/components/dashboard/modals.vue")['default']
export const DashboardWelcome: typeof import("../../veloris-dashboard/components/dashboard/welcome.vue")['default']
export const StoreProductCard: typeof import("../../veloris-dashboard/components/store/product-card.vue")['default']
export const VelorisHello: typeof import("../../veloris-dashboard/components/veloris-hello.vue")['default']
export const Acc: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/acc.vue")['default']
export const Aft: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/aft.vue")['default']
export const Alert: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/alert.vue")['default']
export const Anchor: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/anchor.vue")['default']
export const Bigrid: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/bigrid.vue")['default']
export const Binav: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/binav.vue")['default']
export const Blognav: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/blognav.vue")['default']
export const Breadcrumbs: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/breadcrumbs.vue")['default']
export const Btn: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/btn.vue")['default']
export const Burger: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/burger.vue")['default']
export const ButtonGroup: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/button-group.vue")['default']
export const Cardgrid: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cardgrid.vue")['default']
export const Carousel: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/carousel.vue")['default']
export const Cflex: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cflex.vue")['default']
export const Checkbox: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/checkbox.vue")['default']
export const Chip: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/chip.vue")['default']
export const Chips: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/chips.vue")['default']
export const Column: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/column.vue")['default']
export const ConfirmPassword: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/confirm-password.vue")['default']
export const Content: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/content.vue")['default']
export const CounterInput: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/counter-input.vue")['default']
export const CursorTooltip: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cursor-tooltip.vue")['default']
export const Cursor: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cursor.vue")['default']
export const CustomCss: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/custom-css")['default']
export const Discord: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/discord.vue")['default']
export const DragDiv: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/drag-div.vue")['default']
export const Drop: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/drop.vue")['default']
export const EmailOld: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/email.old.vue")['default']
export const Email: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/email.vue")['default']
export const Error: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/error.vue")['default']
export const Facebook: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/facebook.vue")['default']
export const Field: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/field.vue")['default']
export const Fillout: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/fillout.vue")['default']
export const Flareframe: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/flareframe.vue")['default']
export const Fore: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/fore.vue")['default']
export const Github: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/github.vue")['default']
export const GoogleMap: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/google-map.vue")['default']
export const Grid: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/grid.vue")['default']
export const InfiniteColumn: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/infinite-column.vue")['default']
export const InfiniteRow: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/infinite-row.vue")['default']
export const Instagram: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/instagram.vue")['default']
export const Lchips: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lchips.vue")['default']
export const LeftButton: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/left-button.vue")['default']
export const Lheader: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lheader.vue")['default']
export const LighthouseCircle: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lighthouse-circle.vue")['default']
export const Linkedin: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/linkedin.vue")['default']
export const Loader: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/loader.vue")['default']
export const LogoRolls: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/logo-rolls.vue")['default']
export const Message: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/message.vue")['default']
export const Mflex: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mflex.vue")['default']
export const Mheader: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mheader.vue")['default']
export const Mnav: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mnav.vue")['default']
export const Modal: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/modal.vue")['default']
export const Mpage: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mpage.vue")['default']
export const Name: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/name.vue")['default']
export const NovaInput: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/nova-input.vue")['default']
export const Pages: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/pages.vue")['default']
export const Password: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/password.vue")['default']
export const Rchips: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rchips.vue")['default']
export const Rflex: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rflex.vue")['default']
export const Rheader: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rheader.vue")['default']
export const RightButton: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/right-button.vue")['default']
export const Row: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/row.vue")['default']
export const Search: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/search.vue")['default']
export const Splitrow: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/splitrow.vue")['default']
export const StickyBox: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/sticky-box.vue")['default']
export const StickyContent: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/sticky-content.vue")['default']
export const Submit: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/submit.vue")['default']
export const Success: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/success.vue")['default']
export const Tab: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tab.vue")['default']
export const Tabs: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tabs.vue")['default']
export const Tag: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tag.vue")['default']
export const Toggle: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/toggle.vue")['default']
export const Tooltip: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tooltip.vue")['default']
export const Trigrid: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/trigrid.vue")['default']
export const Trinav: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/trinav.vue")['default']
export const Twitter: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/twitter.vue")['default']
export const TypewriterReplace: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/typewriter-replace.vue")['default']
export const Typewriter: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/typewriter.vue")['default']
export const Whatsapp: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/whatsapp.vue")['default']
export const YoutubeVideo: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/youtube-video.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAdminSidebar: typeof import("../../veloris-dashboard/components/AdminSidebar.vue")['default']
export const LazyAdminTopbar: typeof import("../../veloris-dashboard/components/AdminTopbar.vue")['default']
export const LazyCalendlyEmbed: typeof import("../../veloris-dashboard/components/CalendlyEmbed.vue")['default']
export const LazyChatroom: typeof import("../../veloris-dashboard/components/Chatroom.vue")['default']
export const LazyGravLoader: typeof import("../../veloris-dashboard/components/GravLoader.vue")['default']
export const LazyNavDesktopNav: typeof import("../../veloris-dashboard/components/Nav/DesktopNav.vue")['default']
export const LazyNavMobileNav: typeof import("../../veloris-dashboard/components/Nav/MobileNav.vue")['default']
export const LazyNav: typeof import("../../veloris-dashboard/components/Nav/Nav.vue")['default']
export const LazyNotificationDropdown: typeof import("../../veloris-dashboard/components/NotificationDropdown.vue")['default']
export const LazyOrders: typeof import("../../veloris-dashboard/components/Orders/orders.vue")['default']
export const LazyAddItemDiscardModal: typeof import("../../veloris-dashboard/components/add-item/discard-modal.vue")['default']
export const LazyAddItemImageInputs: typeof import("../../veloris-dashboard/components/add-item/image-inputs.vue")['default']
export const LazyAddItemForm: typeof import("../../veloris-dashboard/components/add-item/item-form.vue")['default']
export const LazyAddItemTags: typeof import("../../veloris-dashboard/components/add-item/tags.vue")['default']
export const LazyAddItemVariations: typeof import("../../veloris-dashboard/components/add-item/variations.vue")['default']
export const LazyAdminDialogs: typeof import("../../veloris-dashboard/components/admin-dialogs.vue")['default']
export const LazyAnalyticsActiveUsersLast30Minutes: typeof import("../../veloris-dashboard/components/analytics/ActiveUsersLast30Minutes.vue")['default']
export const LazyAnalyticsAverageSessionDuration: typeof import("../../veloris-dashboard/components/analytics/AverageSessionDuration.vue")['default']
export const LazyAnalyticsBounceRateByDate: typeof import("../../veloris-dashboard/components/analytics/BounceRateByDate.vue")['default']
export const LazyAnalyticsTotalUsers: typeof import("../../veloris-dashboard/components/analytics/TotalUsers.vue")['default']
export const LazyAnalyticsUsersByChannel: typeof import("../../veloris-dashboard/components/analytics/UsersByChannel.vue")['default']
export const LazyAnalyticsUsersByDate: typeof import("../../veloris-dashboard/components/analytics/UsersByDate.vue")['default']
export const LazyAnalyticsUsersByDeviceChart: typeof import("../../veloris-dashboard/components/analytics/UsersByDeviceChart.vue")['default']
export const LazyAnalyticsViewsByPage: typeof import("../../veloris-dashboard/components/analytics/ViewsByPage.vue")['default']
export const LazyAnalyticsSectionTwo: typeof import("../../veloris-dashboard/components/analytics/section-two.vue")['default']
export const LazyAnalyticsTopSection: typeof import("../../veloris-dashboard/components/analytics/top-section.vue")['default']
export const LazyBlogsEditorPage: typeof import("../../veloris-dashboard/components/blogs/EditorPage.vue")['default']
export const LazyDashboardMessages: typeof import("../../veloris-dashboard/components/dashboard/Messages.vue")['default']
export const LazyDashboardHeader: typeof import("../../veloris-dashboard/components/dashboard/dashboard-header.vue")['default']
export const LazyDashboardFooter: typeof import("../../veloris-dashboard/components/dashboard/footer.vue")['default']
export const LazyDashboardLoader: typeof import("../../veloris-dashboard/components/dashboard/loader.vue")['default']
export const LazyDashboardModals: typeof import("../../veloris-dashboard/components/dashboard/modals.vue")['default']
export const LazyDashboardWelcome: typeof import("../../veloris-dashboard/components/dashboard/welcome.vue")['default']
export const LazyStoreProductCard: typeof import("../../veloris-dashboard/components/store/product-card.vue")['default']
export const LazyVelorisHello: typeof import("../../veloris-dashboard/components/veloris-hello.vue")['default']
export const LazyAcc: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/acc.vue")['default']
export const LazyAft: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/aft.vue")['default']
export const LazyAlert: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/alert.vue")['default']
export const LazyAnchor: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/anchor.vue")['default']
export const LazyBigrid: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/bigrid.vue")['default']
export const LazyBinav: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/binav.vue")['default']
export const LazyBlognav: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/blognav.vue")['default']
export const LazyBreadcrumbs: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/breadcrumbs.vue")['default']
export const LazyBtn: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/btn.vue")['default']
export const LazyBurger: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/burger.vue")['default']
export const LazyButtonGroup: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/button-group.vue")['default']
export const LazyCardgrid: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cardgrid.vue")['default']
export const LazyCarousel: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/carousel.vue")['default']
export const LazyCflex: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cflex.vue")['default']
export const LazyCheckbox: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/checkbox.vue")['default']
export const LazyChip: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/chip.vue")['default']
export const LazyChips: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/chips.vue")['default']
export const LazyColumn: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/column.vue")['default']
export const LazyConfirmPassword: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/confirm-password.vue")['default']
export const LazyContent: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/content.vue")['default']
export const LazyCounterInput: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/counter-input.vue")['default']
export const LazyCursorTooltip: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cursor-tooltip.vue")['default']
export const LazyCursor: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/cursor.vue")['default']
export const LazyCustomCss: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/custom-css")['default']
export const LazyDiscord: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/discord.vue")['default']
export const LazyDragDiv: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/drag-div.vue")['default']
export const LazyDrop: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/drop.vue")['default']
export const LazyEmailOld: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/email.old.vue")['default']
export const LazyEmail: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/email.vue")['default']
export const LazyError: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/error.vue")['default']
export const LazyFacebook: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/facebook.vue")['default']
export const LazyField: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/field.vue")['default']
export const LazyFillout: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/fillout.vue")['default']
export const LazyFlareframe: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/flareframe.vue")['default']
export const LazyFore: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/fore.vue")['default']
export const LazyGithub: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/github.vue")['default']
export const LazyGoogleMap: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/google-map.vue")['default']
export const LazyGrid: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/grid.vue")['default']
export const LazyInfiniteColumn: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/infinite-column.vue")['default']
export const LazyInfiniteRow: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/infinite-row.vue")['default']
export const LazyInstagram: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/instagram.vue")['default']
export const LazyLchips: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lchips.vue")['default']
export const LazyLeftButton: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/left-button.vue")['default']
export const LazyLheader: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lheader.vue")['default']
export const LazyLighthouseCircle: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/lighthouse-circle.vue")['default']
export const LazyLinkedin: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/linkedin.vue")['default']
export const LazyLoader: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/loader.vue")['default']
export const LazyLogoRolls: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/logo-rolls.vue")['default']
export const LazyMessage: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/message.vue")['default']
export const LazyMflex: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mflex.vue")['default']
export const LazyMheader: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mheader.vue")['default']
export const LazyMnav: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mnav.vue")['default']
export const LazyModal: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/modal.vue")['default']
export const LazyMpage: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/mpage.vue")['default']
export const LazyName: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/name.vue")['default']
export const LazyNovaInput: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/nova-input.vue")['default']
export const LazyPages: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/pages.vue")['default']
export const LazyPassword: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/password.vue")['default']
export const LazyRchips: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rchips.vue")['default']
export const LazyRflex: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rflex.vue")['default']
export const LazyRheader: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/rheader.vue")['default']
export const LazyRightButton: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/right-button.vue")['default']
export const LazyRow: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/row.vue")['default']
export const LazySearch: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/search.vue")['default']
export const LazySplitrow: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/splitrow.vue")['default']
export const LazyStickyBox: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/sticky-box.vue")['default']
export const LazyStickyContent: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/sticky-content.vue")['default']
export const LazySubmit: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/submit.vue")['default']
export const LazySuccess: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/success.vue")['default']
export const LazyTab: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tab.vue")['default']
export const LazyTabs: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tabs.vue")['default']
export const LazyTag: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tag.vue")['default']
export const LazyToggle: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/toggle.vue")['default']
export const LazyTooltip: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/tooltip.vue")['default']
export const LazyTrigrid: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/trigrid.vue")['default']
export const LazyTrinav: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/trinav.vue")['default']
export const LazyTwitter: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/twitter.vue")['default']
export const LazyTypewriterReplace: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/typewriter-replace.vue")['default']
export const LazyTypewriter: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/typewriter.vue")['default']
export const LazyWhatsapp: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/whatsapp.vue")['default']
export const LazyYoutubeVideo: typeof import("../node_modules/.c12/github_Veloris_Designs_aph2YalU4I/components/youtube-video.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@22.7.5_eslint@9.12.0_jiti@2.3.3__ioredis@5.4.1__zwgm42rhmfq4kj3orzndavyuza/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
